In [1]:
import pandas as pd

In [2]:
#Carregando o arquivo e exibindo (as primeiras 20 linhas)
df = pd.read_csv("/content/drive/MyDrive/Mini Projeto Final/marketing_campaign.csv - marketing_campaign.csv.csv", sep=",")
df.head(5)

     ID  Year_Birth   Education  ... Z_CostContact  Z_Revenue  Response
0  5524        1957  Graduation  ...             3         11         1
1  2174        1954  Graduation  ...             3         11         0
2  4141        1965  Graduation  ...             3         11         0
3  6182        1984  Graduation  ...             3         11         0
4  5324        1981         PhD  ...             3         11         0

[5 rows x 29 columns]

In [3]:
#Verificando os tipos
df.dtypes

ID                       int64
Year_Birth               int64
Education               object
Marital_Status          object
Income                 float64
Kidhome                  int64
Teenhome                 int64
Dt_Customer             object
Recency                  int64
MntWines                 int64
MntFruits                int64
MntMeatProducts          int64
MntFishProducts          int64
MntSweetProducts         int64
MntGoldProds             int64
NumDealsPurchases        int64
NumWebPurchases          int64
NumCatalogPurchases      int64
NumStorePurchases        int64
NumWebVisitsMonth        int64
AcceptedCmp3             int64
AcceptedCmp4             int64
AcceptedCmp5             int64
AcceptedCmp1             int64
AcceptedCmp2             int64
Complain                 int64
Z_CostContact            int64
Z_Revenue                int64
Response                 int64
dtype: object

In [4]:
#Verificando valores duplicados
df.duplicated().sum()

0

In [5]:
#Verificando valores ausentes.
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [6]:
#Verificando os valores NaN
#Apagando os valores ausentes encontrados (já que são poucas linhas)
df.dropna(inplace=True)
df.isnull().sum()

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

In [7]:
#Verificando dados da coluna "Z_CostContact"
print(df['Z_CostContact'].unique())

[3]

In [8]:
#Verificando dados da coluna "Z_Revenue"
print(df['Z_Revenue'].unique())

[11]

In [9]:
#Já que os valores das colunas "Z_CostContact" e "Z_Revenue"se repetem, 
#não apresentam dados diferentes ao Dataframe, assim é possivel deletar as
#colunas sem perda de dados para comparação
colunas = ['Z_CostContact', 'Z_Revenue']
df.drop(colunas, axis=1, inplace=True)
df.head(5)

     ID  Year_Birth   Education  ... AcceptedCmp2  Complain  Response
0  5524        1957  Graduation  ...            0         0         1
1  2174        1954  Graduation  ...            0         0         0
2  4141        1965  Graduation  ...            0         0         0
3  6182        1984  Graduation  ...            0         0         0
4  5324        1981         PhD  ...            0         0         0

[5 rows x 27 columns]

In [10]:
#Transformando "Dt_Customer" de "object" para "Data"
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])
df.dtypes

ID                              int64
Year_Birth                      int64
Education                      object
Marital_Status                 object
Income                        float64
Kidhome                         int64
Teenhome                        int64
Dt_Customer            datetime64[ns]
Recency                         int64
MntWines                        int64
MntFruits                       int64
MntMeatProducts                 int64
MntFishProducts                 int64
MntSweetProducts                int64
MntGoldProds                    int64
NumDealsPurchases               int64
NumWebPurchases                 int64
NumCatalogPurchases             int64
NumStorePurchases               int64
NumWebVisitsMonth               int64
AcceptedCmp3                    int64
AcceptedCmp4                    int64
AcceptedCmp5                    int64
AcceptedCmp1                    int64
AcceptedCmp2                    int64
Complain                        int64
Response                        int64
dtype: object

In [12]:
#Verificando os dados nas colunas tipo "object"
print(df['Education'].unique())

['Graduation' 'PhD' 'Master' 'Basic' '2n Cycle']

In [13]:
#Verificando os dados nas colunas tipo "object"
print(df['Marital_Status'].unique())

['Single' 'Together' 'Married' 'Divorced' 'Widow' 'Alone' 'Absurd' 'YOLO']

In [14]:
#TRADUÇÃO
#Renomeando as colunas
df.rename(columns= {"Year_Birth":"Ano_Nascimento", 
    "Education":"Escolaridade", 
    "Marital_Status":"Estado_Civil", 
    "Income":"Renda", 
    "Kidhome":"Crianca", 
    "Teenhome":"Adolescente", 
    "Dt_Customer":"Data_Cadastro", 
    "MntWines":"Qtd_Vinho", 
    "MntFruits":"Qtd_Frutas", 
    "MntMeatProducts":"Qtd_Prod_Carne", 
    "MntFishProducts":"Qtd_Prod_Peixe", 
    "MntSweetProducts":"Qtd_Prod_Doce",
    "MntGoldProds":"Qtd_Prod_Gold", 
    "NumDealsPurchases":"Num_Compras_Promocao", 
    "NumWebPurchases":"Num_Compras_Site", 
    "NumCatalogPurchases":"Num_Compras_Catalogo", 
    "NumStorePurchases":"Num_Compra_Loja", 
    "NumWebVisitsMonth":"Num_Visitas_Site_Mensal", 
    "AcceptedCmp3":"Campanha_Aceita_3", 
    "AcceptedCmp4":"Campanha_Aceita_4", 
    "AcceptedCmp5":"Campanha_Aceita_5", 
    "AcceptedCmp1":"Campanha_Aceita_1", 
    "AcceptedCmp2":"Campanha_Aceita_2", 
    "Complain":"Reclamacoes", 
    "Recency":"Dias_Ultima_Compra",
    "Response":"Resposta"},
    inplace=True
    )
df.head(5)

     ID  Ano_Nascimento Escolaridade  ... Campanha_Aceita_2  Reclamacoes  Resposta
0  5524            1957   Graduation  ...                 0            0         1
1  2174            1954   Graduation  ...                 0            0         0
2  4141            1965   Graduation  ...                 0            0         0
3  6182            1984   Graduation  ...                 0            0         0
4  5324            1981          PhD  ...                 0            0         0

[5 rows x 27 columns]

In [15]:
#TRADUÇÃO
#Renomeando as linhas da coluna "Estado Civil"
df['Estado_Civil'].replace('Single', 'Solteiro(a)', inplace=True)
df['Estado_Civil'].replace('Together', 'Namorando', inplace=True)
df['Estado_Civil'].replace('Married', 'Casado(a)', inplace=True)
df['Estado_Civil'].replace('Divorced', 'Divorciado(a)', inplace=True)
df['Estado_Civil'].replace('Widow', 'Viuvo(a)', inplace=True)
df['Estado_Civil'].replace(['Alone', 'Absurd', 'YOLO'], pd.NA, inplace=True)
print(df['Estado_Civil'].unique())

['Solteiro(a)' 'Namorando' 'Casado(a)' 'Divorciado(a)' 'Viuvo(a)' <NA>]

In [16]:
#TRADUÇÃO
#Renomeando as linhas da coluna "Escolaridade"
df['Escolaridade'].replace('Graduation', 'Graducacao', inplace=True)
df['Escolaridade'].replace('PhD', 'Doutorado', inplace=True)
df['Escolaridade'].replace('Master', 'Mestrado', inplace=True)
df['Escolaridade'].replace('Basic', 'Ensino Fundamental', inplace=True)
df['Escolaridade'].replace('2n Cycle', 'Ensino Medio', inplace=True)
print(df['Escolaridade'].unique())

['Graducacao' 'Doutorado' 'Mestrado' 'Ensino Fundamental' 'Ensino Medio']

In [17]:
#Verificando dados das colunas "Campanha_Aceita_1", "Campanha_Aceita_2", "Campanha_Aceita_3", 
#"Campanha_Aceita_4", "Campanha_Aceita_5", "Reclamacoes" e "Respostas", é possivel substituir as rrespostas 
#cpara "sim" ou não" para melhor compreensão

print(df['Campanha_Aceita_1'].unique())
print(df['Campanha_Aceita_2'].unique())
print(df['Campanha_Aceita_3'].unique())
print(df['Campanha_Aceita_4'].unique())
print(df['Campanha_Aceita_5'].unique())
print(df['Reclamacoes'].unique())
print(df['Resposta'].unique())

[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[1 0]

In [18]:
#Substituindo
df['Resposta'].replace({0:'Não', 1:"Sim"}, inplace=True)
df['Reclamacoes'].replace({0:'Não', 1:"Sim"}, inplace=True)
df['Campanha_Aceita_1'].replace({0:'Não', 1:"Sim"}, inplace=True)
df['Campanha_Aceita_2'].replace({0:'Não', 1:"Sim"}, inplace=True)
df['Campanha_Aceita_3'].replace({0:'Não', 1:"Sim"}, inplace=True)
df['Campanha_Aceita_4'].replace({0:'Não', 1:"Sim"}, inplace=True)
df['Campanha_Aceita_5'].replace({0:'Não', 1:"Sim"}, inplace=True)

print(df['Campanha_Aceita_1'].unique())
print(df['Campanha_Aceita_2'].unique())
print(df['Campanha_Aceita_3'].unique())
print(df['Campanha_Aceita_4'].unique())
print(df['Campanha_Aceita_5'].unique())
print(df['Resposta'].unique())

['Não' 'Sim']
['Não' 'Sim']
['Não' 'Sim']
['Não' 'Sim']
['Não' 'Sim']
['Sim' 'Não']

In [19]:
#Condicional de idade: excluindo idades maiores que 110
df[df["Ano_Nascimento"] < 1911]

        ID  Ano_Nascimento  Escolaridade  ... Campanha_Aceita_2  Reclamacoes  Resposta
192   7829            1900  Ensino Medio  ...               Não          Sim       Não
239  11004            1893  Ensino Medio  ...               Não          Não       Não
339   1150            1899     Doutorado  ...               Não          Não       Não

[3 rows x 27 columns]

In [21]:
#Condicional de idade
df.drop([192, 239, 339], inplace=True)

In [22]:
df.head(5)

     ID  Ano_Nascimento Escolaridade  ... Campanha_Aceita_2  Reclamacoes  Resposta
0  5524            1957   Graducacao  ...               Não          Não       Sim
1  2174            1954   Graducacao  ...               Não          Não       Não
2  4141            1965   Graducacao  ...               Não          Não       Não
3  6182            1984   Graducacao  ...               Não          Não       Não
4  5324            1981    Doutorado  ...               Não          Não       Não

[5 rows x 27 columns]

In [26]:
df.dtypes

ID                                  int64
Ano_Nascimento                      int64
Escolaridade                       object
Estado_Civil                       object
Renda                             float64
Crianca                             int64
Adolescente                         int64
Data_Cadastro              datetime64[ns]
Dias_Ultima_Compra                  int64
Qtd_Vinho                           int64
Qtd_Frutas                          int64
Qtd_Prod_Carne                      int64
Qtd_Prod_Peixe                      int64
Qtd_Prod_Doce                       int64
Qtd_Prod_Gold                       int64
Num_Compras_Promocao                int64
Num_Compras_Site                    int64
Num_Compras_Catalogo                int64
Num_Compra_Loja                     int64
Num_Visitas_Site_Mensal             int64
Campanha_Aceita_3                  object
Campanha_Aceita_4                  object
Campanha_Aceita_5                  object
Campanha_Aceita_1                  object
Campanha_Aceita_2                  object
Reclamacoes                        object
Resposta                           object
dtype: object

In [27]:
df.to_csv("/content/drive/MyDrive/Mini Projeto Final/df_marketing_campaing_pandas.csv", sep=",", index=False)