In [ ]:
#BIBLIOTECAS
!pip install pyspark
import pyspark.sql.functions as F
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, DateType
from pyspark.sql.window import Window
import pandas as pd

Collecting pyspark
  Downloading pyspark-3.2.0.tar.gz (281.3 MB)
     |████████████████████████████████| 281.3 MB 33 kB/s
Collecting py4j==0.10.9.2
  Downloading py4j-0.10.9.2-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 51.8 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.2.0-py2.py3-none-any.whl size=281805912 sha256=cdf456cb360ed643d545a8033e3848f85b4e61b657c9e601b1ed0827049f2537
  Stored in directory: /root/.cache/pip/wheels/0b/de/d2/9be5d59d7331c6c2a7c1b6d1a4f463ce107332b1ecd4e80718
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.2 pyspark-3.2.0

In [ ]:
#CONFIGURAR A SPARKSESSION

spark = (SparkSession.builder\
        .master("local")\
        .appName("mini-projeto_final")\
        .config("spark.ui.port", "4050")\
        .getOrCreate())

In [ ]:
#CONFIRMAR A CONFIGURAÇÃO 
spark

In [ ]:
# Abrindo o arquivo
file_location = "/content/drive/MyDrive/Mini Projeto Final/df_marketing_campaing_pandas.csv"
file_type = "csv"

# CSV 
infer_schema = "false"
first_row_is_header = "true"
delimiter = ","

customSchema = StructType([
    StructField("ID", IntegerType(), True),
    StructField("Ano_Nascimento", IntegerType(), True),
    StructField("Escolaridade", StringType(), True),
    StructField("Estado_Civil", StringType(), True),
    StructField("Renda", DoubleType(), True),
    StructField("Crianca", IntegerType(), True),
    StructField("Adolescente", IntegerType(), True),
    StructField("Data_Cadastro", DateType(), True),
    StructField("Dias_Ultima_Compra", IntegerType(), True),
    StructField("Qtd_Vinho", IntegerType(), True),
    StructField("Qtd_Frutas", IntegerType(), True),
    StructField("Qtd_Prod_Carne", IntegerType(), True),
    StructField("Qtd_Prod_Peixe", IntegerType(), True),
    StructField("Qtd_Prod_Doce", IntegerType(), True),
    StructField("Qtd_Prod_Gold", IntegerType(), True),
    StructField("Num_Compras_Promocao", IntegerType(), True),
    StructField("Num_Compras_Site", IntegerType(), True),
    StructField("Num_Compras_Catalogo", IntegerType(), True),
    StructField("Num_Compras_Loja", IntegerType(), True),
    StructField("Num_Compras_Site_Mensal", IntegerType(), True),
    StructField("Campanha_Aceita_3", StringType(), True),
    StructField("Campanha_Aceita_4", StringType(), True),
    StructField("Campanha_Aceita_5", StringType(), True),
    StructField("Campanha_Aceita_1", StringType(), True),
    StructField("Campanha_Aceita_2", StringType(), True),
    StructField("Reclamacoes", StringType(), True),
    StructField("Resposta", StringType(), True),
])

df = spark.read.load(file_location, format="csv", header="true", sep=',', schema=customSchema)

df.show(5)
df.printSchema()

+----+--------------+------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+--------+
|  ID|Ano_Nascimento|Escolaridade|Estado_Civil|  Renda|Crianca|Adolescente|Data_Cadastro|Dias_Ultima_Compra|Qtd_Vinho|Qtd_Frutas|Qtd_Prod_Carne|Qtd_Prod_Peixe|Qtd_Prod_Doce|Qtd_Prod_Gold|Num_Compras_Promocao|Num_Compras_Site|Num_Compras_Catalogo|Num_Compras_Loja|Num_Compras_Site_Mensal|Campanha_Aceita_3|Campanha_Aceita_4|Campanha_Aceita_5|Campanha_Aceita_1|Campanha_Aceita_2|Reclamacoes|Resposta|
+----+--------------+------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+--------+
|5524|          1957|  Graducacao| Solteiro(a)|58138.0|      0|          0|   2012-04-09|                58|      635|        88|           546|           172|           88|           88|                   3|               8|                  10|               4|                      7|              Não|              Não|              Não|              Não|              Não|        Não|     Sim|
|2174|          1954|  Graducacao| Solteiro(a)|46344.0|      1|          1|   2014-08-03|                38|       11|         1|             6|             2|            1|            6|                   2|               1|                   1|               2|                      5|              Não|              Não|              Não|              Não|              Não|        Não|     Não|
|4141|          1965|  Graducacao|   Namorando|71613.0|      0|          0|   2013-08-21|                26|      426|        49|           127|           111|           21|           42|                   1|               8|                   2|              10|                      4|              Não|              Não|              Não|              Não|              Não|        Não|     Não|
|6182|          1984|  Graducacao|   Namorando|26646.0|      1|          0|   2014-10-02|                26|       11|         4|            20|            10|            3|            5|                   2|               2|                   0|               4|                      6|              Não|              Não|              Não|              Não|              Não|        Não|     Não|
|5324|          1981|   Doutorado|   Casado(a)|58293.0|      1|          0|   2014-01-19|                94|      173|        43|           118|            46|           27|           15|                   5|               5|                   3|               6|                      5|              Não|              Não|              Não|              Não|              Não|        Não|     Não|
+----+--------------+------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+--------+
only showing top 5 rows

root
 |-- ID: integer (nullable = true)
 |-- Ano_Nascimento: integer (nullable = true)
 |-- Escolaridade: string (nullable = true)
 |-- Estado_Civil: string (nullable = true)
 |-- Renda: double (nullable = true)
 |-- Crianca: integer (nullable = true)
 |-- Adolescente: integer (nullable = true)
 |-- Data_Cadastro: date (nullable = true)
 |-- Dias_Ultima_Compra: integer (nullable = true)
 |-- Qtd_Vinho: integer (nullable = true)
 |-- Qtd_Frutas: integer (nullable = true)
 |-- Qtd_Prod_Carne: integer (nullable = true)
 |-- Qtd_Prod_Peixe: integer (nullable = true)
 |-- Qtd_Prod_Doce: integer (nullable = true)
 |-- Qtd_Prod_Gold: integer (nullable = true)
 |-- Num_Compras_Promocao: integer (nullable = true)
 |-- Num_Compras_Site: integer (nullable = true)
 |-- Num_Compras_Catalogo: integer (nullable = true)
 |-- Num_Compras_Loja: integer (nullable = true)
 |-- Num_Compras_Site_Mensal: integer (nullable = true)
 |-- Campanha_Aceita_3: string (nullable = true)
 |-- Campanha_Aceita_4: string (nullable = true)
 |-- Campanha_Aceita_5: string (nullable = true)
 |-- Campanha_Aceita_1: string (nullable = true)
 |-- Campanha_Aceita_2: string (nullable = true)
 |-- Reclamacoes: string (nullable = true)
 |-- Resposta: string (nullable = true)

In [ ]:
#Realizar a mudança de nome de pelo menos 2 colunas
df = df.withColumnRenamed("ID", "Id_Cliente").withColumnRenamed("Resposta", "Resposta_Cliente")
df.printSchema()

root
 |-- Id_Cliente: integer (nullable = true)
 |-- Ano_Nascimento: integer (nullable = true)
 |-- Escolaridade: string (nullable = true)
 |-- Estado_Civil: string (nullable = true)
 |-- Renda: double (nullable = true)
 |-- Crianca: integer (nullable = true)
 |-- Adolescente: integer (nullable = true)
 |-- Data_Cadastro: date (nullable = true)
 |-- Dias_Ultima_Compra: integer (nullable = true)
 |-- Qtd_Vinho: integer (nullable = true)
 |-- Qtd_Frutas: integer (nullable = true)
 |-- Qtd_Prod_Carne: integer (nullable = true)
 |-- Qtd_Prod_Peixe: integer (nullable = true)
 |-- Qtd_Prod_Doce: integer (nullable = true)
 |-- Qtd_Prod_Gold: integer (nullable = true)
 |-- Num_Compras_Promocao: integer (nullable = true)
 |-- Num_Compras_Site: integer (nullable = true)
 |-- Num_Compras_Catalogo: integer (nullable = true)
 |-- Num_Compras_Loja: integer (nullable = true)
 |-- Num_Compras_Site_Mensal: integer (nullable = true)
 |-- Campanha_Aceita_3: string (nullable = true)
 |-- Campanha_Aceita_4: string (nullable = true)
 |-- Campanha_Aceita_5: string (nullable = true)
 |-- Campanha_Aceita_1: string (nullable = true)
 |-- Campanha_Aceita_2: string (nullable = true)
 |-- Reclamacoes: string (nullable = true)
 |-- Resposta_Cliente: string (nullable = true)

In [ ]:
#Deverá criar pelo menos duas novas colunas contendo alguma informação relevante 
#sobre as outras colunas já existentes(Use a sua capacidade analítica)
df = df.withColumn("Filhos_Total", F.col("Crianca") + F.col("Adolescente"))
df = df.withColumn("Qtd_Comprada_Total", F.col("Qtd_Vinho") + F.col("Qtd_Frutas") + F.col("Qtd_Prod_Carne") + F.col("Qtd_Prod_Peixe") + F.col("Qtd_Prod_Doce") + F.col("Qtd_Prod_Gold"))
df = df.withColumn("Idade_Cliente", 2021 - F.col("Ano_Nascimento"))

df.head(5)

[Row(Id_Cliente=5524, Ano_Nascimento=1957, Escolaridade='Graducacao', Estado_Civil='Solteiro(a)', Renda=58138.0, Crianca=0, Adolescente=0, Data_Cadastro=datetime.date(2012, 4, 9), Dias_Ultima_Compra=58, Qtd_Vinho=635, Qtd_Frutas=88, Qtd_Prod_Carne=546, Qtd_Prod_Peixe=172, Qtd_Prod_Doce=88, Qtd_Prod_Gold=88, Num_Compras_Promocao=3, Num_Compras_Site=8, Num_Compras_Catalogo=10, Num_Compras_Loja=4, Num_Compras_Site_Mensal=7, Campanha_Aceita_3='Não', Campanha_Aceita_4='Não', Campanha_Aceita_5='Não', Campanha_Aceita_1='Não', Campanha_Aceita_2='Não', Reclamacoes='Não', Resposta_Cliente='Sim', Filhos_Total=0, Qtd_Comprada_Total=1617, Idade_Cliente=64),
 Row(Id_Cliente=2174, Ano_Nascimento=1954, Escolaridade='Graducacao', Estado_Civil='Solteiro(a)', Renda=46344.0, Crianca=1, Adolescente=1, Data_Cadastro=datetime.date(2014, 8, 3), Dias_Ultima_Compra=38, Qtd_Vinho=11, Qtd_Frutas=1, Qtd_Prod_Carne=6, Qtd_Prod_Peixe=2, Qtd_Prod_Doce=1, Qtd_Prod_Gold=6, Num_Compras_Promocao=2, Num_Compras_Site=1, Num_Compras_Catalogo=1, Num_Compras_Loja=2, Num_Compras_Site_Mensal=5, Campanha_Aceita_3='Não', Campanha_Aceita_4='Não', Campanha_Aceita_5='Não', Campanha_Aceita_1='Não', Campanha_Aceita_2='Não', Reclamacoes='Não', Resposta_Cliente='Não', Filhos_Total=2, Qtd_Comprada_Total=27, Idade_Cliente=67),
 Row(Id_Cliente=4141, Ano_Nascimento=1965, Escolaridade='Graducacao', Estado_Civil='Namorando', Renda=71613.0, Crianca=0, Adolescente=0, Data_Cadastro=datetime.date(2013, 8, 21), Dias_Ultima_Compra=26, Qtd_Vinho=426, Qtd_Frutas=49, Qtd_Prod_Carne=127, Qtd_Prod_Peixe=111, Qtd_Prod_Doce=21, Qtd_Prod_Gold=42, Num_Compras_Promocao=1, Num_Compras_Site=8, Num_Compras_Catalogo=2, Num_Compras_Loja=10, Num_Compras_Site_Mensal=4, Campanha_Aceita_3='Não', Campanha_Aceita_4='Não', Campanha_Aceita_5='Não', Campanha_Aceita_1='Não', Campanha_Aceita_2='Não', Reclamacoes='Não', Resposta_Cliente='Não', Filhos_Total=0, Qtd_Comprada_Total=776, Idade_Cliente=56),
 Row(Id_Cliente=6182, Ano_Nascimento=1984, Escolaridade='Graducacao', Estado_Civil='Namorando', Renda=26646.0, Crianca=1, Adolescente=0, Data_Cadastro=datetime.date(2014, 10, 2), Dias_Ultima_Compra=26, Qtd_Vinho=11, Qtd_Frutas=4, Qtd_Prod_Carne=20, Qtd_Prod_Peixe=10, Qtd_Prod_Doce=3, Qtd_Prod_Gold=5, Num_Compras_Promocao=2, Num_Compras_Site=2, Num_Compras_Catalogo=0, Num_Compras_Loja=4, Num_Compras_Site_Mensal=6, Campanha_Aceita_3='Não', Campanha_Aceita_4='Não', Campanha_Aceita_5='Não', Campanha_Aceita_1='Não', Campanha_Aceita_2='Não', Reclamacoes='Não', Resposta_Cliente='Não', Filhos_Total=1, Qtd_Comprada_Total=53, Idade_Cliente=37),
 Row(Id_Cliente=5324, Ano_Nascimento=1981, Escolaridade='Doutorado', Estado_Civil='Casado(a)', Renda=58293.0, Crianca=1, Adolescente=0, Data_Cadastro=datetime.date(2014, 1, 19), Dias_Ultima_Compra=94, Qtd_Vinho=173, Qtd_Frutas=43, Qtd_Prod_Carne=118, Qtd_Prod_Peixe=46, Qtd_Prod_Doce=27, Qtd_Prod_Gold=15, Num_Compras_Promocao=5, Num_Compras_Site=5, Num_Compras_Catalogo=3, Num_Compras_Loja=6, Num_Compras_Site_Mensal=5, Campanha_Aceita_3='Não', Campanha_Aceita_4='Não', Campanha_Aceita_5='Não', Campanha_Aceita_1='Não', Campanha_Aceita_2='Não', Reclamacoes='Não', Resposta_Cliente='Não', Filhos_Total=1, Qtd_Comprada_Total=422, Idade_Cliente=40)]

In [ ]:
df.dtypes

[('Id_Cliente', 'int'),
 ('Ano_Nascimento', 'int'),
 ('Escolaridade', 'string'),
 ('Estado_Civil', 'string'),
 ('Renda', 'double'),
 ('Crianca', 'int'),
 ('Adolescente', 'int'),
 ('Data_Cadastro', 'date'),
 ('Dias_Ultima_Compra', 'int'),
 ('Qtd_Vinho', 'int'),
 ('Qtd_Frutas', 'int'),
 ('Qtd_Prod_Carne', 'int'),
 ('Qtd_Prod_Peixe', 'int'),
 ('Qtd_Prod_Doce', 'int'),
 ('Qtd_Prod_Gold', 'int'),
 ('Num_Compras_Promocao', 'int'),
 ('Num_Compras_Site', 'int'),
 ('Num_Compras_Catalogo', 'int'),
 ('Num_Compras_Loja', 'int'),
 ('Num_Compras_Site_Mensal', 'int'),
 ('Campanha_Aceita_3', 'string'),
 ('Campanha_Aceita_4', 'string'),
 ('Campanha_Aceita_5', 'string'),
 ('Campanha_Aceita_1', 'string'),
 ('Campanha_Aceita_2', 'string'),
 ('Reclamacoes', 'string'),
 ('Resposta_Cliente', 'string'),
 ('Filhos_Total', 'int'),
 ('Qtd_Comprada_Total', 'int'),
 ('Idade_Cliente', 'int')]

In [ ]:
# Deverá utilizar filtros, ordenação e agrupamento, 
# trazendo dados relevantes para o negócio em questão.

#Soma de renda de acordo com Escolaridade
df.groupby(F.col("Escolaridade")).sum("Renda").alias("Soma_Renda").show()

+------------------+-----------+
|      Escolaridade| sum(Renda)|
+------------------+-----------+
|        Graducacao|5.8835937E7|
|         Doutorado|2.6922364E7|
|      Ensino Medio|  9429816.0|
|Ensino Fundamental|  1096538.0|
|          Mestrado|  1.93149E7|
+------------------+-----------+

In [ ]:
#Verificando quantos doutores possuem 1 ou mais filhos

df.filter((F.col("Escolaridade") == "Doutorado") & (F.col("Filhos_Total") >= 1)).show()

+----------+--------------+------------+-------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+
|Id_Cliente|Ano_Nascimento|Escolaridade| Estado_Civil|  Renda|Crianca|Adolescente|Data_Cadastro|Dias_Ultima_Compra|Qtd_Vinho|Qtd_Frutas|Qtd_Prod_Carne|Qtd_Prod_Peixe|Qtd_Prod_Doce|Qtd_Prod_Gold|Num_Compras_Promocao|Num_Compras_Site|Num_Compras_Catalogo|Num_Compras_Loja|Num_Compras_Site_Mensal|Campanha_Aceita_3|Campanha_Aceita_4|Campanha_Aceita_5|Campanha_Aceita_1|Campanha_Aceita_2|Reclamacoes|Resposta_Cliente|Filhos_Total|Qtd_Comprada_Total|Idade_Cliente|
+----------+--------------+------------+-------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+
|      5324|          1981|   Doutorado|    Casado(a)|58293.0|      1|          0|   2014-01-19|                94|      173|        43|           118|            46|           27|           15|                   5|               5|                   3|               6|                      5|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|               422|           40|
|      6177|          1985|   Doutorado|    Casado(a)|33454.0|      1|          0|   2013-08-05|                32|       76|        10|            56|             3|            1|           23|                   2|               4|                   0|               4|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|               169|           36|
|      4855|          1974|   Doutorado|    Namorando|30351.0|      1|          0|   2013-06-06|                19|       14|         0|            24|             3|            3|            2|                   1|               3|                   0|               2|                      9|              Não|              Não|              Não|              Não|              Não|        Não|             Sim|           1|                46|           47|
|      5899|          1950|   Doutorado|    Namorando| 5648.0|      1|          1|   2014-03-13|                68|       28|         0|             6|             1|            1|           13|                   1|               1|                   0|               0|                     20|              Sim|              Não|              Não|              Não|              Não|        Não|             Não|           2|                49|           71|
|      1993|          1949|   Doutorado|    Casado(a)|58607.0|      0|          1|   2012-12-23|                63|      867|         0|            86|             0|            0|           19|                   3|               2|                   3|               9|                      8|              Não|              Sim|              Não|              Não|              Não|        Não|             Não|           1|               972|           72|
|      4047|          1954|   Doutorado|    Casado(a)|65324.0|      0|          1|   2014-11-01|                 0|      384|         0|           102|            21|           32|            5|                   3|               6|                   2|               9|                      4|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|               544|           67|
|      7373|          1952|   Doutorado|Divorciado(a)|46610.0|      0|          2|   2012-10-29|                 8|       96|        12|            96|            33|           22|           43|                   6|               4|                   1|               6|                      6|              Não|              Não|              Não|              Não|              Não|        Não|             Sim|           2|               302|           69|
|      4339|          1970|   Doutorado|    Casado(a)|67353.0|      0|          1|   2013-12-31|                37|      702|        17|           151|             0|            8|           35|                   5|               5|                   6|              12|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|               913|           51|
|      6566|          1954|   Doutorado|    Casado(a)|72550.0|      1|          1|   2012-08-11|                39|      826|        50|           317|            50|           38|           38|                   9|               5|                   2|              12|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           2|              1319|           67|
|      8375|          1968|   Doutorado|    Casado(a)|55954.0|      0|          1|   2014-03-03|                63|      447|         0|            28|             0|            0|           43|                   3|               8|                   2|               6|                      7|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|               518|           53|
|      6518|          1951|   Doutorado|     Viuvo(a)|67680.0|      0|          1|   2013-11-06|                 8|      546|         0|            48|             0|            6|            6|                   1|               7|                   3|               8|                      5|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|               606|           70|
|      8132|          1975|   Doutorado|    Casado(a)|60631.0|      1|          1|   2013-05-04|                88|      565|         6|            65|             0|            6|           19|                   5|               9|                   2|               8|                      7|              Não|              Sim|              Não|              Não|              Não|        Não|             Não|           2|               661|           46|
|      2230|          1970|   Doutorado|    Casado(a)|23626.0|      1|          0|   2014-05-24|                84|       27|         2|            14|             0|            0|            0|                   3|               3|                   1|               3|                      5|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|                43|           51|
|      1016|          1959|   Doutorado|  Solteiro(a)|34554.0|      0|          1|   2014-03-30|                43|       41|         1|             6|             2|            0|            5|                   2|               2|                   0|               3|                      6|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|                55|           62|
|      9215|          1980|   Doutorado|    Casado(a)|43974.0|      1|          0|   2012-12-12|                19|      378|         0|           101|             0|            0|           72|                   5|               6|                   4|               6|                      7|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|               551|           41|
|     11051|          1956|   Doutorado|    Namorando|77376.0|      1|          1|   2014-10-05|                72|      492|        19|           110|            16|           12|           12|                   4|               6|                   3|              10|                      4|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           2|               661|           65|
|      5290|          1964|   Doutorado|    Casado(a)|41551.0|      1|          1|   2013-08-14|                51|      220|         0|            33|             3|            0|           23|                   5|               5|                   1|               5|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           2|               279|           57|
|      9579|          1959|   Doutorado|    Casado(a)|33762.0|      2|          1|   2013-07-07|                61|       53|         1|            34|             2|            0|           16|                   3|               2|                   2|               2|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           3|               106|           62|
|      7660|          1973|   Doutorado|         null|35860.0|      1|          1|   2014-05-19|                37|       15|         0|             8|             4|            2|           20|                   2|               1|                   1|               2|                      5|              Sim|              Não|              Não|              Não|              Não|        Não|             Sim|           2|                49|           48|
|      1461|          1965|   Doutorado|Divorciado(a)|36921.0|      1|          1|   2013-07-28|                74|       17|         1|            12|             3|            1|            4|                   2|               2|                   0|               3|                      7|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           2|                38|           56|
+----------+--------------+------------+-------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+
only showing top 20 rows

In [ ]:
#Somatório, Media, Maior e Menor Renda de acordo com a Escolaridade
(df.groupby(F.col("Escolaridade")).agg(
            F.round(F.sum("Renda"), 2).alias("Soma_Renda"),
            F.round(F.mean("Renda"), 2).alias("Media_Renda"),
            F.max("Renda").alias("Maior_Renda"),
            F.min("Renda").alias("Menor_Renda")
            ).orderBy("Maior_Renda").show())

+------------------+-----------+-----------+-----------+-----------+
|      Escolaridade| Soma_Renda|Media_Renda|Maior_Renda|Menor_Renda|
+------------------+-----------+-----------+-----------+-----------+
|Ensino Fundamental|  1096538.0|   20306.26|    34445.0|     7500.0|
|      Ensino Medio|  9429816.0|   47625.33|    96547.0|     7500.0|
|          Mestrado|  1.93149E7|   52917.53|   157733.0|     6560.0|
|         Doutorado|2.6922364E7|   56088.26|   162397.0|     4023.0|
|        Graducacao|5.8835937E7|   52720.37|   666666.0|     1730.0|
+------------------+-----------+-----------+-----------+-----------+

In [ ]:
#Soma e media de Idade de acordo com a escolaridade
df.groupby(F.col("Escolaridade")).agg(
            F.sum("Idade_Cliente").alias("Soma_Idade"),
            F.round(F.mean("Idade_Cliente"),2).alias("Media_Idade"),
            ).show()

+------------------+----------+-----------+
|      Escolaridade|Soma_Idade|Media_Idade|
+------------------+----------+-----------+
|        Graducacao|     57322|      51.36|
|         Doutorado|     26312|      54.82|
|      Ensino Medio|      9545|      48.21|
|Ensino Fundamental|      2351|      43.54|
|          Mestrado|     19729|      54.05|
+------------------+----------+-----------+

In [ ]:
#Utilizar pelo menos duas Window Functions

In [ ]:
w0 = Window.orderBy(F.col("Idade_Cliente"))
df = df.withColumn("Ordem", F.row_number().over(w0))
df.select(F.col("Ordem"), F.col("Idade_Cliente"), F.col("Id_Cliente"), F.col("Estado_Civil"), F.col("Filhos_Total"), F.col("Qtd_Comprada_Total")).show(25)

+-----+-------------+----------+------------+------------+------------------+
|Ordem|Idade_Cliente|Id_Cliente|Estado_Civil|Filhos_Total|Qtd_Comprada_Total|
+-----+-------------+----------+------------+------------+------------------+
|    1|           25|      9909|   Casado(a)|           0|               122|
|    2|           25|       193|   Casado(a)|           0|                16|
|    3|           26|      8315| Solteiro(a)|           0|                23|
|    4|           26|     10548| Solteiro(a)|           0|               960|
|    5|           26|      5184| Solteiro(a)|           0|                23|
|    6|           26|      4427| Solteiro(a)|           0|              1365|
|    7|           26|      3661| Solteiro(a)|           0|              1435|
|    8|           27|      5067|   Namorando|           0|              1378|
|    9|           27|     10619| Solteiro(a)|           0|              1990|
|   10|           27|      6905|   Namorando|           0|              1004|
|   11|           28|      2669| Solteiro(a)|           0|              1127|
|   12|           28|      4483| Solteiro(a)|           0|              1228|
|   13|           28|     10037| Solteiro(a)|           0|              1127|
|   14|           28|      5080| Solteiro(a)|           0|              1258|
|   15|           28|      7734|        null|           0|              1216|
|   16|           29|      3386|   Casado(a)|           0|               137|
|   17|           29|      8560| Solteiro(a)|           0|               680|
|   18|           29|      3005| Solteiro(a)|           0|              1650|
|   19|           29|      4654|   Namorando|           0|              1253|
|   20|           29|      1379|   Namorando|           0|               241|
|   21|           29|       821| Solteiro(a)|           0|              2077|
|   22|           29|      4136| Solteiro(a)|           1|               119|
|   23|           29|      1384|   Casado(a)|           1|                62|
|   24|           29|      8175|   Casado(a)|           0|               137|
|   25|           29|      4055| Solteiro(a)|           1|                64|
+-----+-------------+----------+------------+------------+------------------+
only showing top 25 rows

In [ ]:
df.withColumn("Percent_Rank", F.percent_rank().over(w0)).show()

+----------+--------------+------------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+-----+------------+
|Id_Cliente|Ano_Nascimento|      Escolaridade|Estado_Civil|  Renda|Crianca|Adolescente|Data_Cadastro|Dias_Ultima_Compra|Qtd_Vinho|Qtd_Frutas|Qtd_Prod_Carne|Qtd_Prod_Peixe|Qtd_Prod_Doce|Qtd_Prod_Gold|Num_Compras_Promocao|Num_Compras_Site|Num_Compras_Catalogo|Num_Compras_Loja|Num_Compras_Site_Mensal|Campanha_Aceita_3|Campanha_Aceita_4|Campanha_Aceita_5|Campanha_Aceita_1|Campanha_Aceita_2|Reclamacoes|Resposta_Cliente|Filhos_Total|Qtd_Comprada_Total|Idade_Cliente|Ordem|Percent_Rank|
+----------+--------------+------------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+-----+------------+
|      9909|          1996|      Ensino Medio|   Casado(a)| 7500.0|      0|          0|   2012-09-11|                24|        3|        18|            14|            15|           22|           50|                   3|               3|                   1|               3|                      9|              Não|              Não|              Não|              Não|              Não|        Não|             Sim|           0|               122|           25|    1|         0.0|
|       193|          1996|Ensino Fundamental|   Casado(a)|14421.0|      0|          0|   2014-02-17|                81|        0|         0|             2|             3|            3|            8|                   1|               1|                   0|               2|                      5|              Sim|              Não|              Não|              Não|              Não|        Não|             Não|           0|                16|           25|    2|         0.0|
|      8315|          1995|        Graducacao| Solteiro(a)|34824.0|      0|          0|   2014-03-26|                65|        4|         2|            11|             2|            0|            4|                   1|               1|                   0|               2|                      6|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|                23|           26|    3|         0.1|
|     10548|          1995|        Graducacao| Solteiro(a)|71163.0|      0|          0|   2014-09-03|                30|      283|        17|           372|           138|          106|           44|                   1|               3|                   8|              12|                      1|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               960|           26|    4|         0.1|
|      5184|          1995|        Graducacao| Solteiro(a)|34824.0|      0|          0|   2014-03-26|                65|        4|         2|            11|             2|            0|            4|                   1|               1|                   0|               2|                      6|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|                23|           26|    5|         0.1|
|      4427|          1995|      Ensino Medio| Solteiro(a)|83257.0|      0|          0|   2012-09-18|                56|      536|        27|           590|            38|          107|           67|                   1|               5|                  10|              12|                      6|              Sim|              Não|              Sim|              Não|              Não|        Sim|             Sim|           0|              1365|           26|    6|         0.1|
|      3661|          1995|      Ensino Medio| Solteiro(a)|80617.0|      0|          0|   2012-12-10|                42|      594|        51|           631|            72|           55|           32|                   1|               4|                   6|               8|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              1435|           26|    7|         0.1|
|      5067|          1994|        Graducacao|   Namorando|80134.0|      0|          0|   2014-02-14|                11|      966|        26|           282|            52|           26|           26|                   1|               2|                   7|              11|                      5|              Não|              Sim|              Sim|              Sim|              Sim|        Não|             Não|           0|              1378|           27|    8|        0.35|
|     10619|          1994|        Graducacao| Solteiro(a)|95529.0|      0|          0|   2012-03-12|                29|      770|        29|           890|           250|           27|           24|                   1|               7|                   3|               7|                      3|              Não|              Não|              Sim|              Não|              Não|        Não|             Sim|           0|              1990|           27|    9|        0.35|
|      6905|          1994|        Graducacao|   Namorando|80685.0|      0|          0|   2012-08-22|                55|      241|        45|           604|            34|           26|           54|                   1|               6|                   4|              10|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              1004|           27|   10|        0.35|
|      2669|          1993|        Graducacao| Solteiro(a)|74293.0|      0|          0|   2014-04-05|                66|      375|       152|           335|            93|           91|           81|                   1|               5|                   4|               6|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              1127|           28|   11|         0.5|
|      4483|          1993|        Graducacao| Solteiro(a)|72354.0|      0|          0|   2013-04-17|                67|      315|        26|           473|           220|           12|          182|                   1|               2|                  10|               6|                      1|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              1228|           28|   12|         0.5|
|     10037|          1993|        Graducacao| Solteiro(a)|74293.0|      0|          0|   2014-04-05|                66|      375|       152|           335|            93|           91|           81|                   1|               5|                   4|               6|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              1127|           28|   13|         0.5|
|      5080|          1993|        Graducacao| Solteiro(a)|70515.0|      0|          0|   2013-10-21|                12|      420|         0|           452|           182|           64|          140|                   1|               6|                   6|               4|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Sim|           0|              1258|           28|   14|         0.5|
|      7734|          1993|        Graducacao|        null|79244.0|      0|          0|   2012-12-19|                58|      471|       102|           125|           212|           61|          245|                   1|               4|                  10|               7|                      1|              Não|              Não|              Sim|              Sim|              Não|        Não|             Sim|           0|              1216|           28|   15|         0.5|
|       821|          1992|          Mestrado| Solteiro(a)|92859.0|      0|          0|   2012-10-19|                46|      962|        61|           921|            52|           61|           20|                   1|               5|                   4|              12|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              2077|           29|   16|        0.75|
|      1379|          1992|          Mestrado|   Namorando|42670.0|      0|          0|   2013-04-27|                12|      154|         2|            46|            20|            4|           15|                   1|               4|                   2|               4|                      4|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               241|           29|   17|        0.75|
|      3386|          1992|        Graducacao|   Casado(a)|34935.0|      0|          0|   2013-06-21|                71|       34|         4|            66|             3|           10|           20|                   1|               2|                   1|               4|                      7|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               137|           29|   18|        0.75|
|      8560|          1992|        Graducacao| Solteiro(a)|48789.0|      0|          0|   2012-10-09|                94|      351|        16|           156|             7|            5|          145|                   1|               6|                   4|               7|                      6|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               680|           29|   19|        0.75|
|      4654|          1992|        Graducacao|   Namorando|75114.0|      0|          0|   2013-07-11|                40|      571|        12|           523|            63|           60|           24|                   1|               3|                  10|               5|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              1253|           29|   20|        0.75|
+----------+--------------+------------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+-----+------------+
only showing top 20 rows

In [ ]:
w1 = Window.partitionBy(F.col("Estado_Civil")).orderBy(F.col("Filhos_Total"))
df = df.withColumn("Rank", F.row_number().over(w1))
df.select(F.col("Rank"), F.col("Renda"), F.col("Num_Compras_Promocao"), F.col("Num_Compras_Catalogo"), F.col("Num_Compras_Loja"), F.col("Num_Compras_Site_Mensal"), F.col("Qtd_Comprada_Total")).show(15)

+----+-------+--------------------+--------------------+----------------+-----------------------+------------------+
|Rank|  Renda|Num_Compras_Promocao|Num_Compras_Catalogo|Num_Compras_Loja|Num_Compras_Site_Mensal|Qtd_Comprada_Total|
+----+-------+--------------------+--------------------+----------------+-----------------------+------------------+
|   1|79244.0|                   1|                  10|               7|                      1|              1216|
|   2|65487.0|                   3|                   5|               6|                      2|              1169|
|   3|34176.0|                   4|                   0|               4|                      6|                89|
|   4|48432.0|                   5|                   1|               6|                      8|               424|
|   5|48432.0|                   5|                   1|               6|                      8|               424|
|   6|61331.0|                   5|                   1|               6|                      8|               632|
|   7|35860.0|                   2|                   1|               2|                      5|                49|
|   1| 7500.0|                   1|                   0|               3|                      8|                61|
|   2|17323.0|                   1|                   0|               3|                      8|                46|
|   3|37040.0|                   1|                   2|               5|                      8|               316|
|   4|84618.0|                   1|                   9|              10|                      2|              1672|
|   5|68657.0|                   1|                   5|               9|                      7|              1196|
|   6| 7500.0|                   3|                   1|               3|                      9|               122|
|   7|79143.0|                   1|                   9|              13|                      3|              1693|
|   8|66991.0|                   3|                   8|               6|                      3|              1253|
+----+-------+--------------------+--------------------+----------------+-----------------------+------------------+
only showing top 15 rows

In [ ]:
df.printSchema()

root
 |-- Id_Cliente: integer (nullable = true)
 |-- Ano_Nascimento: integer (nullable = true)
 |-- Escolaridade: string (nullable = true)
 |-- Estado_Civil: string (nullable = true)
 |-- Renda: double (nullable = true)
 |-- Crianca: integer (nullable = true)
 |-- Adolescente: integer (nullable = true)
 |-- Data_Cadastro: date (nullable = true)
 |-- Dias_Ultima_Compra: integer (nullable = true)
 |-- Qtd_Vinho: integer (nullable = true)
 |-- Qtd_Frutas: integer (nullable = true)
 |-- Qtd_Prod_Carne: integer (nullable = true)
 |-- Qtd_Prod_Peixe: integer (nullable = true)
 |-- Qtd_Prod_Doce: integer (nullable = true)
 |-- Qtd_Prod_Gold: integer (nullable = true)
 |-- Num_Compras_Promocao: integer (nullable = true)
 |-- Num_Compras_Site: integer (nullable = true)
 |-- Num_Compras_Catalogo: integer (nullable = true)
 |-- Num_Compras_Loja: integer (nullable = true)
 |-- Num_Compras_Site_Mensal: integer (nullable = true)
 |-- Campanha_Aceita_3: string (nullable = true)
 |-- Campanha_Aceita_4: string (nullable = true)
 |-- Campanha_Aceita_5: string (nullable = true)
 |-- Campanha_Aceita_1: string (nullable = true)
 |-- Campanha_Aceita_2: string (nullable = true)
 |-- Reclamacoes: string (nullable = true)
 |-- Resposta_Cliente: string (nullable = true)
 |-- Filhos_Total: integer (nullable = true)
 |-- Qtd_Comprada_Total: integer (nullable = true)
 |-- Idade_Cliente: integer (nullable = true)
 |-- Ordem: integer (nullable = false)
 |-- Rank: integer (nullable = false)

In [ ]:
df.show(20)

+----------+--------------+------------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+-----+----+
|Id_Cliente|Ano_Nascimento|      Escolaridade|Estado_Civil|  Renda|Crianca|Adolescente|Data_Cadastro|Dias_Ultima_Compra|Qtd_Vinho|Qtd_Frutas|Qtd_Prod_Carne|Qtd_Prod_Peixe|Qtd_Prod_Doce|Qtd_Prod_Gold|Num_Compras_Promocao|Num_Compras_Site|Num_Compras_Catalogo|Num_Compras_Loja|Num_Compras_Site_Mensal|Campanha_Aceita_3|Campanha_Aceita_4|Campanha_Aceita_5|Campanha_Aceita_1|Campanha_Aceita_2|Reclamacoes|Resposta_Cliente|Filhos_Total|Qtd_Comprada_Total|Idade_Cliente|Ordem|Rank|
+----------+--------------+------------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+-----+----+
|      7734|          1993|        Graducacao|        null|79244.0|      0|          0|   2012-12-19|                58|      471|       102|           125|           212|           61|          245|                   1|               4|                  10|               7|                      1|              Não|              Não|              Sim|              Sim|              Não|        Não|             Sim|           0|              1216|           28|   15|   1|
|      4369|          1957|          Mestrado|        null|65487.0|      0|          0|   2014-10-01|                48|      240|        67|           500|           199|            0|          163|                   3|               3|                   5|               6|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              1169|           64| 1790|   2|
|        92|          1988|        Graducacao|        null|34176.0|      1|          0|   2014-12-05|                12|        5|         7|            24|            19|           14|           20|                   4|               3|                   0|               4|                      6|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|                89|           33|   93|   3|
|       492|          1973|         Doutorado|        null|48432.0|      0|          1|   2012-10-18|                 3|      322|         3|            50|             4|            3|           42|                   5|               7|                   1|               6|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           1|               424|           48|  911|   4|
|     11133|          1973|         Doutorado|        null|48432.0|      0|          1|   2012-10-18|                 3|      322|         3|            50|             4|            3|           42|                   5|               7|                   1|               6|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Sim|           1|               424|           48|  913|   5|
|      7660|          1973|         Doutorado|        null|35860.0|      1|          1|   2014-05-19|                37|       15|         0|             8|             4|            2|           20|                   2|               1|                   1|               2|                      5|              Sim|              Não|              Não|              Não|              Não|        Não|             Sim|           2|                49|           48|  845|   6|
|       433|          1958|          Mestrado|        null|61331.0|      1|          1|   2013-10-03|                42|      534|         5|            47|             0|            5|           41|                   5|              11|                   1|               6|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           2|               632|           63| 1706|   7|
|      9909|          1996|      Ensino Medio|   Casado(a)| 7500.0|      0|          0|   2012-09-11|                24|        3|        18|            14|            15|           22|           50|                   3|               3|                   1|               3|                      9|              Não|              Não|              Não|              Não|              Não|        Não|             Sim|           0|               122|           25|    1|   1|
|       193|          1996|Ensino Fundamental|   Casado(a)|14421.0|      0|          0|   2014-02-17|                81|        0|         0|             2|             3|            3|            8|                   1|               1|                   0|               2|                      5|              Sim|              Não|              Não|              Não|              Não|        Não|             Não|           0|                16|           25|    2|   2|
|      3386|          1992|        Graducacao|   Casado(a)|34935.0|      0|          0|   2013-06-21|                71|       34|         4|            66|             3|           10|           20|                   1|               2|                   1|               4|                      7|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               137|           29|   18|   3|
|      8175|          1992|        Graducacao|   Casado(a)|34935.0|      0|          0|   2013-06-21|                71|       34|         4|            66|             3|           10|           20|                   1|               2|                   1|               4|                      7|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               137|           29|   24|   4|
|      2802|          1992|      Ensino Medio|   Casado(a)|87000.0|      0|          0|   2012-12-15|                61|      196|        25|           607|            67|           17|           49|                   1|               4|                   6|               7|                      2|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               961|           29|   27|   5|
|      9214|          1991|        Graducacao|   Casado(a)|42691.0|      0|          0|   2013-08-16|                48|      179|         2|            64|            38|           17|           58|                   1|               5|                   1|               6|                      5|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               358|           30|   32|   6|
|      4552|          1991|        Graducacao|   Casado(a)|51373.0|      0|          0|   2013-06-22|                37|       83|         2|           101|            64|           26|          117|                   1|               3|                   5|               3|                      4|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               393|           30|   42|   7|
|      9529|          1990|        Graducacao|   Casado(a)|73687.0|      0|          0|   2013-11-28|                 8|      559|       153|           503|           218|           13|          181|                   1|               3|                   9|               9|                      2|              Não|              Não|              Não|              Sim|              Não|        Não|             Sim|           0|              1627|           31|   44|   8|
|      8151|          1990|Ensino Fundamental|   Casado(a)|24279.0|      0|          0|   2012-12-29|                 6|       16|        36|            21|            20|           62|          108|                   1|               4|                   1|               3|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|               263|           31|   45|   9|
|      8278|          1990|         Doutorado|   Casado(a)|74214.0|      0|          0|   2012-08-26|                 3|      863|        83|           547|            86|           99|           33|                   1|               8|                   2|               5|                      5|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|              1711|           31|   48|  10|
|      3068|          1990|        Graducacao|   Casado(a)|18351.0|      0|          0|   2013-10-29|                 1|        1|        12|             9|             0|           14|            7|                   1|               2|                   0|               3|                      7|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|                43|           31|   49|  11|
|      2253|          1990|        Graducacao|   Casado(a)|18929.0|      0|          0|   2013-02-16|                15|       32|         0|             8|            23|            4|           18|                   1|               1|                   0|               4|                      6|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|                85|           31|   50|  12|
|      2431|          1990|        Graducacao|   Casado(a)|18222.0|      0|          0|   2012-12-31|                70|       12|         4|            19|            12|            6|           14|                   1|               2|                   0|               3|                      8|              Não|              Não|              Não|              Não|              Não|        Não|             Não|           0|                67|           31|   55|  13|
+----------+--------------+------------------+------------+-------+-------+-----------+-------------+------------------+---------+----------+--------------+--------------+-------------+-------------+--------------------+----------------+--------------------+----------------+-----------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------+----------------+------------+------------------+-------------+-----+----+
only showing top 20 rows

In [22]:
df.write.format("com.databricks.spark.csv").option("header", "true")\
                                            .option("inferschema", "true")\
                                            .option("delimiter", ",")\
                                            .save("/content/drive/MyDrive/Mini Projeto Final/df_marketing_campaing_pyspark.csv")

In [ ]:
df1